# general
VERTICAL_TILES = 12
HORIZONTAL_TILES = 21
TILE_SIZE = 64
HEIGHT = VERTICAL_TILES * TILE_SIZE
WIDTH = HORIZONTAL_TILES * TILE_SIZE
FPS = 60

# buttons
BUTTON_BG_COLOR = '#33323d'
BUTTON_LINE_COLOR = '#f5f1de'